### get all blogs
GET http://localhost:3001/api/blogs

###create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "makes you feel alone",
  "author": "shawty",
  "url": "falty.net",
  "likes": 23232,
  "userId": "6510788d8e545025326675c6"
}

###create a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username" : "miukkai",
  "name": "Matti Luukkainen",
  "password" : "matti"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username" : "mii",
  "name": "Matti Luukkainen",
  "password" : "mid"
}

###get all users
GET http://localhost:3001/api/users

###log in
post http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "miukkai",
  "password": "matti"
}

### create a new blog with a logged in user
post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pdWtrYWkiLCJpZCI6IjY1MTA3ODhkOGU1NDUwMjUzMjY2NzVjNiIsImlhdCI6MTY5NjI1MjY2Nn0.85Z2M-kK--XWwmqX85GmnfoK2EOE6cP478Fykvmn2vc

{
  "title": "its you",
  "author": "homeboi",
  "url": "vscode.ma",
  "likes": 5455
}
