GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "makes you feel alone",
  "author": "shawty",
  "url": "falty.net",
  "likes": 23232,
  "userId": "6510788d8e545025326675c6"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username" : "miukkai",
  "name": "Matti Luukkainen",
  "password" : "matti"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username" : "mii",
  "name": "Matti Luukkainen",
  "password" : "mid"
}

###

GET http://localhost:3001/api/users
